version: '3.8'
volumes:
  db-data: {}
services:
  db-host: 
    build: ./db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - $MYSQLDB_DOCKER_PORT:$MYSQLDB_LOCAL_PORT
    environment:
      MYSQL_DATABASE: $MYSQLDB_DATABASE
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
    volumes:
      - db-data:/var/lib/mysql
  api:
    depends_on:
      - db-host
    build:
      dockerfile: Dockerfile
      context: ./$API_CONTEXT
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - $API_DOCKER_PORT:$API_LOCAL_PORT
    volumes:
      - /usr/src/app/node_modules
      - ./api/app:/usr/src/app
  app:
    build:
      dockerfile: Dockerfile
      context: ./$APP_CONTEXT
    restart: unless-stopped
    env_file: ./$APP_CONTEXT/.env
    ports:
      - $APP_DOCKER_PORT:$APP_LOCAL_PORT
    volumes:
      - /usr/src/app/node_modules
      - ./$APP_CONTEXT:/usr/src/app
