import Head from "next/head";
import BookSlug from "./BookSlug";

export default function BookSlugContainer() {
  return (
    <>
      <Head>
        <title>Book Detail | Contact list</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BookSlug/>
    </>
  );
}
